# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: grpcgateway.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11grpcgateway.proto\x12\x0bgrpcgateway\"\x10\n\x0ePredictRequest\"\x11\n\x0fPredictResponse\"\x1c\n\x0eGetDataRequest\x12\n\n\x02id\x18\x01 \x01(\t\"\x11\n\x0fGetDataResponse\"\x1c\n\x0eGetUserRequest\x12\n\n\x02id\x18\x01 \x01(\t\"\x11\n\x0fGetUserResponse2[\n\x11PredictionService\x12\x46\n\x07Predict\x12\x1b.grpcgateway.PredictRequest\x1a\x1c.grpcgateway.PredictResponse\"\x00\x32U\n\x0b\x44\x61taService\x12\x46\n\x07GetData\x12\x1b.grpcgateway.GetDataRequest\x1a\x1c.grpcgateway.GetDataResponse\"\x00\x32X\n\x0e\x41\x63\x63ountService\x12\x46\n\x07GetUser\x12\x1b.grpcgateway.GetUserRequest\x1a\x1c.grpcgateway.GetUserResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'grpcgateway_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PREDICTREQUEST._serialized_start=34
  _PREDICTREQUEST._serialized_end=50
  _PREDICTRESPONSE._serialized_start=52
  _PREDICTRESPONSE._serialized_end=69
  _GETDATAREQUEST._serialized_start=71
  _GETDATAREQUEST._serialized_end=99
  _GETDATARESPONSE._serialized_start=101
  _GETDATARESPONSE._serialized_end=118
  _GETUSERREQUEST._serialized_start=120
  _GETUSERREQUEST._serialized_end=148
  _GETUSERRESPONSE._serialized_start=150
  _GETUSERRESPONSE._serialized_end=167
  _PREDICTIONSERVICE._serialized_start=169
  _PREDICTIONSERVICE._serialized_end=260
  _DATASERVICE._serialized_start=262
  _DATASERVICE._serialized_end=347
  _ACCOUNTSERVICE._serialized_start=349
  _ACCOUNTSERVICE._serialized_end=437
# @@protoc_insertion_point(module_scope)
