# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import proto_files.acc_hougang_pb2 as acc_hougang_pb2


class acc_HougangStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Login = channel.unary_unary(
                '/acc_hougang.acc_Hougang/Login',
                request_serializer=acc_hougang_pb2.Login_Request.SerializeToString,
                response_deserializer=acc_hougang_pb2.Login_Reply.FromString,
                )
        self.Register = channel.unary_unary(
                '/acc_hougang.acc_Hougang/Register',
                request_serializer=acc_hougang_pb2.Register_Request.SerializeToString,
                response_deserializer=acc_hougang_pb2.Register_Reply.FromString,
                )


class acc_HougangServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Login(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Register(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_acc_HougangServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Login': grpc.unary_unary_rpc_method_handler(
                    servicer.Login,
                    request_deserializer=acc_hougang_pb2.Login_Request.FromString,
                    response_serializer=acc_hougang_pb2.Login_Reply.SerializeToString,
            ),
            'Register': grpc.unary_unary_rpc_method_handler(
                    servicer.Register,
                    request_deserializer=acc_hougang_pb2.Register_Request.FromString,
                    response_serializer=acc_hougang_pb2.Register_Reply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'acc_hougang.acc_Hougang', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class acc_Hougang(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Login(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/acc_hougang.acc_Hougang/Login',
            acc_hougang_pb2.Login_Request.SerializeToString,
            acc_hougang_pb2.Login_Reply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Register(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/acc_hougang.acc_Hougang/Register',
            acc_hougang_pb2.Register_Request.SerializeToString,
            acc_hougang_pb2.Register_Reply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
