# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: account.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\raccount.proto\x12\x07\x61\x63\x63ount\"0\n\rLogin_Request\x12\r\n\x05\x65mail\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"3\n\x0bLogin_Reply\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x13\n\x0bhouseholdID\x18\x02 \x01(\t\"\xae\x01\n\x10Register_Request\x12\x12\n\nfirst_name\x18\x01 \x01(\t\x12\x11\n\tlast_name\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t\x12\x10\n\x08password\x18\x04 \x01(\t\x12\x0e\n\x06region\x18\x05 \x01(\t\x12\x0f\n\x07\x61\x64\x64ress\x18\x06 \x01(\t\x12\x0c\n\x04unit\x18\x07 \x01(\t\x12\x0e\n\x06postal\x18\x08 \x01(\t\x12\x13\n\x0bhouseholdID\x18\t \x01(\t\"5\n\x0eRegister_Reply\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x12\n\nerror_type\x18\x02 \x01(\t2\x84\x01\n\x07\x61\x63\x63ount\x12\x37\n\x05Login\x12\x16.account.Login_Request\x1a\x14.account.Login_Reply\"\x00\x12@\n\x08Register\x12\x19.account.Register_Request\x1a\x17.account.Register_Reply\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'account_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _LOGIN_REQUEST._serialized_start=26
  _LOGIN_REQUEST._serialized_end=74
  _LOGIN_REPLY._serialized_start=76
  _LOGIN_REPLY._serialized_end=127
  _REGISTER_REQUEST._serialized_start=130
  _REGISTER_REQUEST._serialized_end=304
  _REGISTER_REPLY._serialized_start=306
  _REGISTER_REPLY._serialized_end=359
  _ACCOUNT._serialized_start=362
  _ACCOUNT._serialized_end=494
# @@protoc_insertion_point(module_scope)
