# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ml.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x08ml.proto\x12\x02ml\"6\n\x11UsageData_Request\x12\x13\n\x0bhouseholdID\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61ys\x18\x02 \x01(\x05\"6\n\tUsageData\x12\x11\n\ttimestamp\x18\x01 \x01(\t\x12\x16\n\x0e\x65lectric_usage\x18\x02 \x01(\x02\"/\n\x0fUsageData_Reply\x12\x1c\n\x05items\x18\x01 \x03(\x0b\x32\r.ml.UsageData\"-\n\x16PredictionData_Request\x12\x13\n\x0bhouseholdID\x18\x01 \x01(\t\"E\n\x18PredictionDataIndividual\x12\x11\n\ttimestamp\x18\x01 \x01(\t\x12\x16\n\x0e\x65lectric_usage\x18\x02 \x01(\x02\"H\n\x1bPredictionDataHouseholdType\x12\x11\n\ttimestamp\x18\x01 \x01(\t\x12\x16\n\x0e\x65lectric_usage\x18\x02 \x01(\x02\"r\n\x14PredictionData_Reply\x12*\n\x04item\x18\x01 \x03(\x0b\x32\x1c.ml.PredictionDataIndividual\x12.\n\x05item2\x18\x02 \x03(\x0b\x32\x1f.ml.PredictionDataHouseholdType2\x8f\x01\n\x02ml\x12<\n\x0cGetUsageData\x12\x15.ml.UsageData_Request\x1a\x13.ml.UsageData_Reply\"\x00\x12K\n\x11GetPredictionData\x12\x1a.ml.PredictionData_Request\x1a\x18.ml.PredictionData_Reply\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ml_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _USAGEDATA_REQUEST._serialized_start=16
  _USAGEDATA_REQUEST._serialized_end=70
  _USAGEDATA._serialized_start=72
  _USAGEDATA._serialized_end=126
  _USAGEDATA_REPLY._serialized_start=128
  _USAGEDATA_REPLY._serialized_end=175
  _PREDICTIONDATA_REQUEST._serialized_start=177
  _PREDICTIONDATA_REQUEST._serialized_end=222
  _PREDICTIONDATAINDIVIDUAL._serialized_start=224
  _PREDICTIONDATAINDIVIDUAL._serialized_end=293
  _PREDICTIONDATAHOUSEHOLDTYPE._serialized_start=295
  _PREDICTIONDATAHOUSEHOLDTYPE._serialized_end=367
  _PREDICTIONDATA_REPLY._serialized_start=369
  _PREDICTIONDATA_REPLY._serialized_end=483
  _ML._serialized_start=486
  _ML._serialized_end=629
# @@protoc_insertion_point(module_scope)
